version: '3.5'
services:
 six_jars:
  build: .
  ports:
   - "4000:4000"
  volumes:
   - .:/app
  environment:
   - ENV=development
   - PORT=4000
   - DB=mongodb://hainq:Haideptrai1@ds143474.mlab.com:43474/6jars
   - SECRET='my-secret-string'
networks:
 default:
  name: six_jars